app:
  name: "bluebell"
  mode: "dev"
  port: 8081
  version: "v0.0.1"
  start_time: "2021-12-08"
  machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 100
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13306
  user: "root"
  password: "root1234"
  dbname: "webapp"
  max_connection: 200
  max_maintain: 30

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
